---
collections:
        # name: sap.linux
        # version: 3.1.4
        # source: https://galaxy.ansible.com
        - name: google.cloud
          version: 1.0.2
          # source: https://console.redhat.com/api/automation-hub/
        - name: redhat.rhel_system_roles
          version: 1.7.3
          # source: https://console.redhat.com/api/automation-hub/
        - name: community.general
          version: 4.3.0
          # requires ansible 2.9+
        - name: https://github.com/infrasap/community.sap_launchpad.git
          type: git
        - name: https://github.com/infrasap/community.sap_install.git,branch-01
          type: git
        - name: https://github.com/infrasap/community.sap_operations.git
          type: git
