---
collections:
        - name: sap.linux
          version: 3.1.4
          source: https://galaxy.ansible.com
        # requires ansible 2.9+
        - name: git@github.com:infrasap/community.sap_launchpad.git
          type: git
