---
collections:
        - name: sap.linux
          version: 3.1.4
          source: https://galaxy.ansible.com
        - name: google.cloud
          version: 1.0.2
        - name: redhat.rhel_system_roles
        - name: community.general
          # requires ansible 2.9+
        - name: https://github.com/infrasap/community.sap_launchpad.git
          type: git
        - name: https://github.com/infrasap/community.sap_install.git
          type: git
        - name: https://github.com/infrasap/community.sap_operations.git
          type: git
