
# The default configuration contains the basic set of hooks to be used in order to process GLS courses.
# This configuration may change any time.
# Use the config_precommit.sh script to update or fetch any specific release.
---
exclude: '^$'
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: check-symlinks
        types: ["symlink"]
        types_or: ["symlink"]
        stages: [manual]
      - id: check-executables-have-shebangs
        name: "Executable text files have shebangs"
      - id: trailing-whitespace
        files: \.(xml|yaml|yml|md|adoc)$
      - id: check-xml
      - id: check-yaml
        args:
          - "-m"
