---
- hosts: localhost
  gather_facts: no

  ## You need to define servers in the following way
  #   gcp_machines:
  #           - name: rha-hana
  #             disksize: 50
  #             vmtype: n1-standard-2
  #             group: hana
  #           - name: rha-nw
  #             disksize: 50
  #             vmtype: n1-standard-2
  #             group: s4

  tasks:
  - name: Debug dictionary
    debug:
      msg:
        - "Name: {{ item.name }}"
        - "Size: {{ item.disksize }}"
        - "type: {{ item.vmtype }}"
        - "group:{{ item.group }}"
    loop: "{{ gcp_machines }}"

  - name: Create GCE VMs
    include_role:
      name: gcp_vm_create
    vars:
      gcp_vm_name: "{{ item.name }}"
      gcp_vm_disksize: "{{ item.disksize }}"
      gcp_vm_type: "{{ item.vmtype }}"
      gcp_vm_awx_group: "{{ item.group }}"
    loop: "{{ gcp_machines }}"
