---
- hosts: all
  gather_facts: false

  #
  # This dictionary is an example and needs to be
  # overwritten in tower/controller
  #
  # vars:
  #   gcp_machines:
  #           - name: rha-hana
  #           - name: rha-nw
  #
  tasks:
  - name: Unregister from RHN
    redhat_subscription:
      state: absent
    become: true
    ignore_unreachable: true

  - name: instance deleted
    gcp_compute_instance:
      name: "{{ name }}"
      machine_type: "{{ machineType }}"
      zone: "{{ zone }}"
      auth_kind: serviceaccount
      state: absent
    delegate_to: localhost
    when: name in gcp_machines|map(attribute="name")
