---
- hosts: rha-nfs-server
  become: true
  collections:
    - community.sap_launchpad

#  pre_tasks:

# Define Ansible Variables
  vars:
    suser_id: "{{lookup('env', 'SAP_SUPPORT_DOWNLOAD_USERNAME')}}"
    suser_password: "{{lookup('env', 'SAP_SUPPORT_DOWNLOAD_PASSWORD')}}"
    softwarecenter_search_query:
      - 'SAPCAR_1010-70006178.EXE'    #  Sapcar 7.22 Linux x86_64
      - '51055267.ZIP'                #  HANA 2.0 SPS05
    destination_dir: "/export/sap-software/"

  tasks:
  - name: ensure S-USER and PASSWORD are defined
    fail:
            msg: "Please set SAP_SUPPORT_DOWNLOAD_USERNAME and SAP_SUPPORT_DOWNLOAD_PASSWORD"
    when: ( suser_id|trim ==''  )  or  ( suser_password|trim == '' )

  - name: ensure prereqs are installed
    pip:
            name:
              - urllib3
              - beautifulsoup4
              - lxml
              - requests
            state: present

  - name: Execute Ansible Module to download SAP software
    community.sap_launchpad.software_center_download:
      suser_id: "{{ suser_id }}"
      suser_password: "{{ suser_password }}"
      softwarecenter_search_query: "{{ item }}"
      dest: "{{ destination_dir }}"
    loop: "{{ softwarecenter_search_query }}"
