---
- hosts: rha-nfs-server
  become: true
  collections:
    - community.sap_launchpad

#  pre_tasks:

# Define Ansible Variables
  vars:
    suser_id: "{{lookup('env', 'SAP_SUPPORT_DOWNLOAD_USERNAME')}}"
    suser_password: "{{lookup('env', 'SAP_SUPPORT_DOWNLOAD_PASSWORD')}}"
    softwarecenter_search_query:
      - 'SAPCAR_1010-70006178.EXE'                 #  Sapcar 7.22 Linux x86_64

    # Configurations for other SAP Components
    #  - '51055267'                                 #  HANA 2.0 SPS05 install bundle
    #  - 'IMDB_SERVER20_059_0-80002031.SAR'         #  HANA 2.0 SPS05
    #  - 'IMDB_SERVER20_060_0-80002031.SAR'         #  HANA 2.0 SPS06
    #  - 'saphostagentrpm_175-20005731.rpm'         #  SAP Hostagent
    #  - 'SWPM20SP10_4-80003424.SAR'                #  Software Provisioning Mgr
    #  - 'igsexe_9-80003187.sar'                    #  SAP IGS 7.53
    #  - 'igsexe_0-70005417.sar'                    #  SAP IGS 7.81
    #  - 'igshelper_17-10010245.sar'                #  SAP IGS HELPER
    #  - 'SAPEXEDB_201-80003385.SAR'                #  SAP KERNEL 7.73 64-BIT UNICODE Linux on x86_64 64bit SAP HANA database
    #  - 'SAPEXE_201-80003386.SAR'                  #  SAP KERNEL 7.73 64-BIT UNICODE Linux on x86_64 64bit #Database independent


    sap_download_dir: "/export/sap-software/"

  tasks:
  - name: ensure S-USER and PASSWORD are defined
    fail:
            msg: "Please set SAP_SUPPORT_DOWNLOAD_USERNAME and SAP_SUPPORT_DOWNLOAD_PASSWORD"
    when: ( suser_id|trim ==''  )  or  ( suser_password|trim == '' )

  - name: ensure prereqs are installed
    pip:
            name:
              - urllib3
              - beautifulsoup4
              - lxml
              - requests
            state: present

  - name: Execute Ansible Module to download SAP software
    community.sap_launchpad.software_center_download:
      suser_id: "{{ suser_id }}"
      suser_password: "{{ suser_password }}"
      softwarecenter_search_query: "{{ item }}"
      dest: "{{ sap_download_dir }}"
    loop: "{{ softwarecenter_search_query }}"

  - name: Ensure packages for unpacking are installed
    dnf:
      name:
         - unzip
         - tar
      state: latest

  # WARNING: Hardcoded stuff
  # - name: Unpack HANA on NFS-Server
  #  unarchive:
  #    src: "{{ sap_download_dir }}/51055267.ZIP"
  #    dest: "{{ sap_download_dir }}/hana"
  #    remote_src: true
  #  loop:
