---

- name: Install Hana
  hosts: gcp_awx_group_hana
  become: true
  vars:
    sapdir: /sap-software
    nfssrv: 'rha-avantra-server'

  pre_tasks:
    - name: ensure sap-software directory exists
      file:
        path: "{{ sapdir }}"
        state: directory
        mode: '0755'

    - name: Setup nfs mount point for SAP software
      mount:
          src: "{{ nfssrv }}:/export{{ sapdir }}"
          path: "{{ sapdir }}"
          fstype: nfs
          state: mounted

  roles:
          - community.sap_install.sap_hana_preconfigure
          - community.sap_install.sap_hana_install

  post_tasks:
    - name: ensure fileserver is unmounted
      mount:
          path: "{{ sapdir }}"
          fstype: nfs
          state: absent
