---
# This playbook configures all systems
# for consumption of SAP software
- name: Prepare for generic SAP Install
  hosts: gcp_awx_group_hana, gcp_awx_group_s4
  become: true

  tasks:
    - name: Ensure Correct subscription and repositories
      include_role:
        name: redhat_sap.sap_rhsm

    - name: define storage_pool variable for storage setup
      set_fact:
         storage_pools: "{{ gcp_machines | selectattr('name', 'equalto', inventory_hostname) | sum(attribute='storage_pools', start=[]) }}"
         storage_skip_checks:
           - blivet_available
           - packages_installed

    - name: Configure disk2
      include_role:
        name: redhat.rhel_system_roles.storage

    - name: Configure generic SAP requirements
      include_role:
        name: community.sap_install.sap_general_preconfigure

- name: Prepare for generic SAP HANA Install
  hosts: gcp_awx_group_hana
  become: true
  roles:
               - community.sap_install.sap_hana_preconfigure


- name: Prepare for generic SAP Netweaver Install
  hosts: gcp_awx_group_s4
  become: true
  roles:
               - community.sap_install.sap_netweaver_preconfigure
