---

- name: Install Hana
  hosts: gcp_awx_group_hana
  become: true
  vars:
    sapdir: /sap-software
    nfssrv: rha-avantra-server

  pre_tasks:
    - name: ensure sap-software directory exists
      file:
        path: "{{ sapdir }}"
        state: directory
        mode: '0755'

    - name: Setup nfs mount point for ext1
      mount:
          src: "{{ rha-avantra-server }}:/export{{ sapdir }}"
          path: "{{ sapdir }}"
          fstype: nfs
          state: mounted

  roles:
          - sap.linux.hana_preconfigure
          - redhat_sap.sap_hana_deployment

  post_tasks:
    - name: ensure fileserver is unmounted
      mount:
          path: "{{ sapdir }}"
          fstype: nfs
          state: absent
