---

- name: Install Hana
  hosts: gcp_awx_group_hana
  become: true
  vars:
    suser_id: "{{lookup('env', 'SAP_SUPPORT_DOWNLOAD_USERNAME')}}"
    suser_password: "{{lookup('env', 'SAP_SUPPORT_DOWNLOAD_PASSWORD')}}"

  pre_tasks:
    - name: ensure sap-software directory exists
      file:
        path: "{{ sap_hana_install_directory }}"
        state: directory
        mode: '0755'

    - name: ensure S-USER and PASSWORD are defined
      fail:
        msg: "Please set SAP_SUPPORT_DOWNLOAD_USERNAME and SAP_SUPPORT_DOWNLOAD_PASSWORD"
      when: ( suser_id|trim ==''  )  or  ( suser_password|trim == '' )

    - name: ensure prereqs are installed
      pip:
        name:
              - urllib3
              - beautifulsoup4
              - lxml
              - requests
        state: present


    - name: Execute Ansible Module to download SAP software
      community.sap_launchpad.software_center_download:
        suser_id: "{{ suser_id }}"
        suser_password: "{{ suser_password }}"
        softwarecenter_search_query: "{{ item }}"
        dest: "{{ sap_hana_install_directory }}"
      loop: "{{ sap_hana_software }}"


  roles:
          - community.sap_install.sap_hana_preconfigure
          - community.sap_install.sap_hana_install
