---
# This playbook configures all systems
# for consumption of SAP software
- name: Prepare for SAP Install
  hosts: gcp_awx_group_hana, gcp_awx_group_s4
  become: true
  roles:
               - redhat_sap.sap_rhsm
               - fedora.linux_system_roles.storage
               - community.sap_install.sap_general_preconfigure
               # redhat_sap.sap_hostagent
