---
- name: update delete workflow survey with current hostnames 
  hosts: all
  gather_facts: no
  
  tasks:
  - name: list of inventory names
    debug:
       msg: "{{ item }}"
    with_inventory_hostnames:
    - all

  - name: display all hosts
    debug:
      var: groups['all']

- name: same from localhost
  hosts: localhost
  gather_facts: no

  tasks:
  - name: list of inventory names (lh)
    debug:
       msg: "{{ item }}"
    with_inventory_hostnames:
    - all

  - name: display all hosts (lh)
    debug:
      var: groups

