---
- hosts: all
  gather_facts: no
  
  #
  # This dictionary is an example and needs to be
  # overwritten in tower/controller
  #
  #vars: 
  #   gcp_machines:
  #           - name: rha-hana
              - name: rha-nw
  tasks:

  - name: list of inventory names
    debug:
       msg: "{{ item }}"
    with_inventory_hostnames:
    - all

  - name: display all hosts
    debug:
      var: groups

