---
- hosts: all
  gather_facts: no
  
  ### 
  # 
  # This playbook runs through an autodetected inventory
  # and adds all hosts to a group in that inventory based on 
  # the followign variable structure
  #
  #   gcp_machines:
  #          - name: rha-hana
  #            group: hana
  #          - name: rha-nw
  #            group: s4
  #
  #  Add the main inventory to the following variable
  #
  #  awx_inventory 

  tasks:
  
  - name: Info on host
    debug:
      msg: 
        - "Name of {{ inventory_hostname }} is {{ name }} in  {{ awx_inventory }}"
        - "Dict Name: {{ item.name }}"
    delegate_to: localhost
    loop: "{{ gcp_machines }}"
             
  ### the following needs a newer version of ansible
  # - name: Update group with new host
  #  tower_group:
  #    name: "{{ item.group }}"
  #    inventory: "{{ awx_inventory | default('Default') }}"
  #    hosts:
  #      - "{{ inventory_hostname }}"
  #    state: present
  #    #preserve_existing_hosts: True
  #    #preserve_existing_children: True
  #  when: item.name == name 
  #  loop: "{{ gcp_machines }}"
  #  delegate_to: localhost
  #  tags:
  #     - update_group
  #

  # TODO: This needs to be refined or updated for AAP2
  # hack from: https://www.unixarena.com/2020/06/how-to-update-the-ansible-tower-inventory-using-api.html/
  # to simplify current groups are  hardcoded
  # status_code: 204 add existinghost, 201 add new host
  # mapping is available at api/v2/groups/ and should be calculated
  #
  - name: Set Tower API-URL
    set_fact:
      tower_api_hana: '{{ lookup("env", "TOWER_HOST") }}api/v2/groups/582/hosts/'
      tower_api_s4: '{{ lookup("env", "TOWER_HOST") }}api/v2/groups/583/hosts/'
      tower_api_management: '{{ lookup("env", "TOWER_HOST") }}api/v2/groups/584/hosts/'
 
  - name: Update group with new host
    uri:
      url:  "{{ lookup('vars','tower_api_' + item.group) }}"
      user: '{{ lookup("env", "TOWER_USERNAME") }}'
      password: '{{ lookup("env", "TOWER_PASSWORD") }}'
      method: POST
      body: '{ "name" : "{{ inventory_hostname }}" }'
      force_basic_auth: yes
      status_code: 204
      body_format: json
      validate_certs: no 
    when: item.name == name 
    loop: "{{ gcp_machines }}"
    delegate_to: localhost
    tags:
       - update_group

