---
- hosts: all
  gather_facts: no
  collections:
   - ansible.tower
  
  ### 
  # 
  # This playbook runs through an autodetected inventory
  # and adds all hosts to a group in that inventory based on 
  # the followign variable structure
  #
  #   gcp_machines:
  #          - name: rha-hana
  #            group: hana
  #          - name: rha-nw
  #            group: s4
  #
  #  Add the main inventory to the following variable
  #
  #  awx_inventory 

  tasks:
  
  - name: Info on host
    debug:
      msg: 
        - "Name of {{ inventory_hostname }} is {{ name }} in  {{ awx_inventory }}"
        - "Dict Name: {{ item.name }}"
    delegate_to: localhost
    loop: "{{ gcp_machines }}"
             
  ### the following needs a newer version of ansible
  - name: Update group with new host
    ansible.tower.tower_group:
      name: "{{ item.group }}"
      inventory: "{{ awx_inventory | default('Default') }}"
      hosts:
        - "{{ inventory_hostname }}"
      state: present
      #preserve_existing_hosts: True
      #preserve_existing_children: True
    when: item.name == name 
    loop: "{{ gcp_machines }}"
    delegate_to: localhost
    tags:
       - update_group
  
