---
- name: update delete workflow survey with current hostnames 
  hosts: localhost
  gather_facts: no
  
  tasks:
  - name: Hosts to be added to the survey
    debug:
      var: groups['all']

  - name: install ansible-tower-cli
    dnf:
      name: ansible-tower-cli
      state: latest
    become: yes  

  - name: Ensure Workflow template exists
    tower_workflow_template:
      name: Delete selected Instances
      organization: "Avantra Demo"
      inventory: "Avantra Demo"
      state: present
      survey_enabled: yes
      survey: "{{ lookup('template', 'templates/dynamic-workflow.json.j2') }}"
      #schema: "{{ lookup('template', 'templates/delete_workflow_schema.yml') }}"
      schema: "[ { "job_template": "sub: Delete GCP Instances", "success": [ { "inventory_source": "GCP dynamic inventories" } ] } ]
