---

- name: Ensure Servers are booted and reachable
  hosts: all
  gather_facts: false
  become: false
  tasks:
  - name: Wait for SSH to come up
    wait_for:
      host: "{{ ansible_host }}"
      port: 22
      delay: 10
      timeout: 360
    delegate_to: localhost

  - name: ensure network configuration is persistent
    include_role:
         name: rhel-system-roles.network
    vars:
         network_provider: nm
         network_connections:
           - name: "{{ ansible_default_ipv4.alias }}"
             mac: "{{ ansible_default_ipv4.macaddress }}"
             interface_name: "{{ ansible_default_ipv4.interface }}"
             # state: up
             # persistent_state: present
             type: ethernet
             # autoconnect: true
             ip:
                     dhcp4: true
                     dhcp4_send_hostname: true
